<?php
use Drupal\Component\Utility\Html;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;


/**
 * Implements hook_form_FORM_ID_alter().
 */
function user_module_form_node_admission_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 
   // exit;
    $current_path = \Drupal::service('path.current')->getPath();
  if($current_path == '/node/add/admission'){ $form['#title'] = t('APPLICATION FORM MFA');}
   if($current_path == '/admission-form-bfa') $form['#title'] = t('APPLICATION FORM BFA');
  $form['#theme'] = ['node_admission_forms'];
   $form['#validate'][] = '_form_validation_admission';
  $form['actions']['submit']['#submit'][] = '_form_submit_admission';
  $form['title']['widget'][0]['value']['#description'] = t('(in block letters as in Senior School Certificate)');
    
}

function _form_validation_admission(&$form, FormStateInterface $form_state)
{
  # code...
}

function _form_submit_admission(&$form, FormStateInterface $form_state)
{
  \Drupal::service('messenger')->addMessage("Application Submit Succesfully");
$url = Url::fromUserInput('/admission-form-mfa', [], ['absolute' => 'true']);
     $response = new RedirectResponse($url->toString());
      $response->send();
}

/**
 * Implements hook_theme().
 */
function user_module_theme($existing, $type, $theme, $path) {
  return array(
    'node_admission_forms' => [
      'render element' => 'form',
    ],
  );
}



/**
 * Implements hook_preprocess().
 */
function user_module_preprocess(&$variables, $hook) {
 
 $current_path = \Drupal::service('path.current')->getPath();
  if($current_path == '/node/add/admission' || $current_path == '/admission-form-bfa'){
  if($hook == 'input' || $hook == 'select' || $hook == 'textarea') {
     if($variables['element']['#type'] == 'submit'){
     $variables['attributes']['class'][] = Html::cleanCssIdentifier('btn-primary');
     }
    if($variables['element']['#type'] != 'checkbox'){
     $variables['attributes']['class'][] = Html::cleanCssIdentifier('form-control');
     }
    
}
}

}